### PR TITLE
Fix memory leak and coding error in demo

### PR DESCRIPTION
**Pull request by DRNadler**

### CODE REVIEW

**Comment by asmwarrior** [comment]
Hi, I think this patch file need to be modified.

Because in the Code::Blocks IDE, the GUI designer is called wxSmith, When you drag the component, the code will be automatically generated. 

~~~
//(*xxx)
...
//(*xxx)
~~~

The code between those comments are automatically generated by wxSmith.

In the discussion with heob's author, it looks like adding `UnInit();` function can fix some memory leak issue, but from the wx's document, the `UnInit();` will be called by the wx's framework when exit, I'm not sure why.

Does adding the `UnInit();` fix all the memory leak issue you mentioned in the issue comment:

https://github.com/GitHubLionel/wxMathPlot/issues/46#issuecomment-2308433269

**Comment by asmwarrior** [comment]
Another thing about the construction of the wxFrame is that in wxSmith generated code, it use something called "two-step construction", I mean it use the `Create` function to create the frame, see document here: [wxWidgets: wxFrame Class Reference](https://docs.wxwidgets.org/latest/classwx_frame.html)

So, I think the base class's constructor(wxFrame::wxFrame()) does not need to be specified.

**Comment by DRNadler** [comment]
Hi @GitHubLionel - I didn't realize you were using wxSmith.
The code generated by wxSmith is _really unfortunate_ because its generated code:
- is co-mingled in the same source as your code - terrible idea
- leaks memory

Really bad.

I use wxFormBuilder because it works really well and generates base classes you derive from. All generated code is in separate files, so not co-mingled with your code. Thus your code is the absolute minimum needed to add application behavior by adding your application-specific stuff to derived classes (application data members and override methods), making it more readable and maintainable. And I have not had wxFormBuilder-generated code leak memory. wxFormBuilder is very activ
[20240829_forLionel_wxLogAnalyzer.zip](https://github.com/user-attachments/files/16818021/20240829_forLionel_wxLogAnalyzer.zip)
ely maintained and full-featured.

You should give https://github.com/wxFormBuilder/wxFormBuilder a try!
I've attached a sample app I use as a template (I should update to use AUI), and also my current app (does use AUI) for you to look at; hope you find this helpful to see the above points:
[wxTemplate.zip](https://github.com/user-attachments/files/16817936/wxTemplate.zip)

Thanks!
Best Regards, Dave

**Comment by asmwarrior** [comment]
Hi, if the generated code of wxSmith has some memory leak issue, We(I) can try to fix them. Because all the wxSmith code base is in the Code::Blocks' code repo.

I'm currently not sure which code wxSmith generate is wrong here, can you explain it? Thanks.

**Comment by GitHubLionel** [comment]
I can not merge the corrections because there are in the auto-generated code by wxSmith.
But the correction is simply to add `AuiManager1->UnInit();`, that what I do.

For `wxFormBuilder`, yes I know it but historically I used C::B with wxSmith because the old version of wxMathplot was integrated in the IDE. 
Note that I also use wxGlade, and it is my preferred because generated code is very short. IDE is basic but has the essentials.

**Comment by DRNadler** [comment]
Instead of wasting time on a really bad tool, why don't you just use wxFormBuilder for the demo? Much cleaner!

**Comment by GitHubLionel** [comment]
Note : I try to compile `wxLogAnalyzer` but several missing : `LogfileRecords.hpp`, `lib/nlohmann/json.hpp`, `helpers/MinMax.hpp` and maybe more.

**Comment by DRNadler** [comment]
@GitHubLionel - I provided these samples for you to see how much cleaner code is using wxFormBuilder, and how wxFormBuilder code uses AUI manager without leaking memory. Not to compile...

**Comment by GitHubLionel** [comment]
I see. You prefer to have a base class with no code and all virtual functions. Then inherit from the base class and fill the virtual functions. You use wxFormBuilder only to create the IHM.

**Comment by DRNadler** [comment]
The base class contains (and keeps out of application code modules) all the boilerplate GUI construction and destruction. Thus the only code in the application is... that I really need for the application. Putting generating code (bracketed, with some escape sequence) into the application source has proven a disaster about a million times in the history of computing...

**Comment by GitHubLionel** [comment]
Yes, I understand. Mix owner code and generated code is not a good idea !

**Pull request closed without merging**
