### PR TITLE
Documentation corrections, fix formatting complaint

### PR DESCRIPTION
**Pull request by DRNadler**

### CODE REVIEW

**Comment by DRNadler** [comment]
Compiles without warnings in your toolchain now?

**Comment by GitHubLionel** [comment]
Yes it is ok, no warning.
But your formatting is very different from mine, so at the end we will have a very heterogenous code :-1:

**Comment by DRNadler** [comment]
I try to make things readable for my own sanity and maintainability.
Compare some of the code in wxMathPlot to this:
image
Lots of extra lines would hugely reduce readability and maintainability...

**Comment by GitHubLionel** [comment]
Yes !
But when you get or use an existing library, you don't expect that the author change all his framework to be conform to yours ! lol
The library has its own formatting.
And you have your own formatting for your private code.

**Comment by DRNadler** [comment]
We have the opportunity to modernize the code so it will be more usable and maintainable in future...

**Pull request merged**
