### PR TITLE
Window resize notification working plus minor cleanups

### PR DESCRIPTION
**Pull request by DRNadler**
**DRY**: Please see: https://en.wikipedia.org/wiki/Don%27t_repeat_yourself
If you find yourself cutting and pasting, or repeating the same bits of code,
you're doing something wrong...

I'll try make a quick video of how these mods are used in my application tomorrow...

### CODE REVIEW

**Comment by DRNadler** [comment]
Here's a quick example: https://www.nadler.com/backups/2024-08-15_AnalysisProgramProgress.mp4
As I move the mouse across the timeseries, I need to highlight the matching point in the track window.
Not sure how to do that yet...

**Comment by GitHubLionel** [comment]
Sorry but my english is very poor and I have some trouble to understand your speak.
But the problem is that you want to communicate between two plots. One part can be solve using `m_OnUserMouseAction`  in the timeseries. Other part is maybe to use `wxDCOverlay` in the track window. See the thread of  [asmwarrior ](https://github.com/GitHubLionel/wxMathPlot/issues/33)

**Comment by GitHubLionel** [comment]
Maybe we can directly introduce to mpWindow a callback when the plot is resizing in the same way I added a callback for the mouse events ?
Other idea, we may add in mpWindow the ability to communicate with another plot by sending some events ...

**Comment by DRNadler** [comment]
Hi Lionel - That is what I have already implemented in mpWindow.
Use is illustrated in the sample code above and in the video.
Did you have something different in mind?
Code already implemented in mpWindow is this:
```
    /// To be notified of displayed bounds changes (after user zoom etc),
    /// override this callback in your derived class and look at new value of m_desired.
    /// Useful for keeping multiple plots in sync when user zooms.
    virtual void DesiredBoundsHaveChanged() {}; 
```

**Comment by GitHubLionel** [comment]
`DesiredBoundsHaveChanged()` is a virtual function that you override in your own mpWindow (that's what I understood).
I thought more to a callback like I do in "user mouse event".

Otherwise, but it is just a think, we can add in mpWindow a function to communicate with another mpWindow. Something like : 
`typedef std::function<void(void *Sender, ... parameters ?)> mpOnMessageToOtherWindow;`
In protected mpWindow section : 
`mpWindow *m_OtherWindow;
mpOnMessageToOtherWindow m_OnMessageToOtherWindow;`
In public mpWindow section : 
`void SetOtherWindow(const mpWindow &win, const mpOnMessageToOtherWindow &MessageToOtherWindowHandler) {m_OtherWindow = win; m_OnMessageToOtherWindow = mpOnMessageToOtherWindow }`
and then in `CheckAndReportDesiredBoundsChanges` you will have : 
`m_OtherWindow->m_OnMessageToOtherWindow(this, ... parameters);`

well something like that but I maybe totally wrong !!

**Comment by DRNadler** [comment]
FYI: https://www.nadler.com/backups/2024-08-18_AnalysisProgramProgress.mp4
Note: For some reason mouse isn't captured at beginning of video, only after a few seconds of recording.

**Comment by GitHubLionel** [comment]
Very impressive :+1:

**Pull request merged**
